### ISSUE TITLE
source?

### ISSUE THREAD

**Issue by gcb** [jameshilliard/actiontec_opensrc_mi424wr-rev-i_fw-40-21-18#1]
hi. where did you get hold of this? their site only list newer versions http://opensource.actiontec.com/mi424wri.html

thank you

**Comment by jameshilliard** [comment]
I'm pretty sure that's where I got it from, I think they don't keep every release however.

**Comment by gcb** [comment]
thanks! i had emailed them before finding this. thanks for uploading.

verizon is still shipping modems with this older version.

**Comment by jameshilliard** [comment]
Yeah, the source is incomplete anyways though so you can't use it as is and actiontec doesn't seem interested in fixing it. Kind of curious, what are you trying to do with it?
